using System;
using System.ComponentModel.DataAnnotations;

namespace TitanHelpApplication.Models
{
    public class Ticket
    {
        // Data Layer: Primary Key, Auto-generated by SQLite
        [Key]
        public int Id { get; set; }

        // Presentation: Required for UI validation
        // Data Layer: Maps to a string with a 100-character limit
        [Required(ErrorMessage = "Requester name is required")]
        [StringLength(100)]
        public string Name { get; set; }

        // Application: Auto-populated with the current date/time
        [Required]
        [Display(Name = "Date Created")]
        public DateTime Date { get; set; } = DateTime.Now;

        // Presentation: Multi-line text input required
        // Data Layer: Maps to a string with a 1000-character limit
        [Required(ErrorMessage = "Problem description is required")]
        [StringLength(1000)]
        [Display(Name = "Problem Description")]
        public string ProblemDescription { get; set; }

        // Application: Default value is "Open"
        [Required]
        public string Status { get; set; } = "Open";

        // Presentation: Rendered as a dropdown (Low, Medium, High)
        [Required]
        public TicketPriority Priority { get; set; }
    }

    public enum TicketPriority
    {
        Low,
        Medium,
        High
    }
}




