// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TitanHelpApplication.Data;

#nullable disable

namespace TitanHelpApplication.Migrations
{
    [DbContext(typeof(TicketDbContext))]
    partial class TicketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("TitanHelpApplication.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ticket");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice Smith",
                            Priority = "Medium",
                            ProblemDescription = "Printer jammed",
                            Status = "Open"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bob Jones",
                            Priority = "High",
                            ProblemDescription = "Email login failed",
                            Status = "Open"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
